apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerochain

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - nats.yaml
  - minio.yaml
  - zerochaind-statefulset.yaml
  - zerochaind-service.yaml
  - ingress.yaml
  - job-example.yaml
