apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: zerochain
spec:
  serviceName: nats
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: http
          args:
            - "--http_port"
            - "8222"
          livenessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: zerochain
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: http
      port: 8222
      targetPort: 8222
